feat: add Code Block tests
nl-design-system/candidate pull request #141
Opened 2024-11-12 18:47 UTC by matijs

2024-11-15 18:30 UTC, Robbert requested changes

2024-11-15 18:30 UTC, Robbert commented on packages/components-react/code-block-react/src/code-block.test.tsx
> +  it('renders an HTML pre element that contains an HTML code element', () => {
De test-implementatie checkt niet of het een HTML code element is

2024-11-15 18:30 UTC, Robbert commented on packages/components-react/code-block-react/src/code-block.test.tsx
> +    const codeBlockContent = codeBlock?.querySelector(':only-child');
Wil je zoiets?
```suggestion
    const codeBlockContent = codeBlock?.querySelector<HTMLElement>('code:only-child');
```

2024-11-15 19:16 UTC, matijs commented on packages/components-react/code-block-react/src/code-block.test.tsx
> +    const codeBlockContent = codeBlock?.querySelector(':only-child');
Ik was die `code` vergeten maar… TIL dat `querySelector` generics slikt… 😲

2024-11-17 13:46 UTC, Robbert submitted a review, later dismissed

2024-11-17 13:46 UTC, Robbert commented on packages/components-react/code-block-react/src/code-block.test.tsx
> +const testCode = "import { CodeBlock } from '@nl-design-system-candidate/code-block';";
```suggestion
const testCode = "import { CodeBlock } from '@nl-design-system-candidate/code-block-react';";
```

2024-11-17 13:59 UTC, Robbert approved these changes

2024-11-17 14:00 UTC, merged