feat: add Number Badge component
nl-design-system/candidate pull request #148
Opened 2024-11-13 16:08 UTC by matijs

- Add @nl-design-system-candidate/number-badge-react
- Add @nl-design-system-candidate/number-badge-css
- Add @nl-design-system-candidate/number-badge-docs
- Add @nl-design-system-candidate/number-badge-tokens

2024-11-15 18:41 UTC, Robbert requested changes

2024-11-15 18:41 UTC, Robbert commented on packages/components-react/number-badge-react/src/number-badge.tsx
> +      const { value, ...dataRestProps } = restProps as DataHTMLAttributes<HTMLDataElement>;
Die `as` is misschien niet nodig?

```tsx
const isNumberBadgePropsForData = (arg: NumberBadgeProps): arg is isNumberBadgePropsForData => 'value' in arg;

if (isNumberBadgePropsForData(props)) {
      const { value, ...dataRestProps } = restProps;
```

2024-11-15 19:31 UTC, matijs commented on packages/components-react/number-badge-react/src/number-badge.tsx
> +      const { value, ...dataRestProps } = restProps as DataHTMLAttributes<HTMLDataElement>;
I like.

2024-11-16 08:56 UTC, Robbert approved these changes

2024-11-16 08:56 UTC, merged