docs: add anatomy
nl-design-system/candidate pull request #156
Opened 2024-11-14 13:36 UTC by matijs

- code-block
- code
- color-sample
- data-badge
- heading
- link
- mark
- paragraph
- skip-link

2024-11-15 18:43 UTC, Robbert requested changes

2024-11-15 18:43 UTC, Robbert commented on packages/docs/code-block-docs/docs/anatomy.md
> +1. Code block
```suggestion
1. Code Block
```

2024-11-16 07:36 UTC, matijs commented
Ik weet niet hoe nuttig het is om een iframe/svg toe te voegen. Zie bijvoorbeeld Paragraph. GitHub toont het [niet](https://github.com/nl-design-system/candidate/blob/feat/docs-anatomy/packages/docs/paragraph-docs/docs/anatomy.md)

2024-11-16 08:00 UTC, Robbert commented
@matijs Ik inderdaad dat het beter is om deze vanuit Storybook te renderen, via de preview.tsx template of via mdx

2024-11-16 08:01 UTC, Robbert commented
@matijs Laten we deze PR eerst mergen zonder iframes

2024-11-16 14:59 UTC, matijs commented
Done!

2024-11-17 13:59 UTC, Robbert approved these changes

2024-11-17 13:59 UTC, merged