docs: Add aliases + anatomies for heading 1 t/m 6
nl-design-system/candidate pull request #344
Opened 2024-12-09 20:41 UTC by hidde

2024-12-09 21:43 UTC, matijs requested changes

2024-12-09 21:43 UTC, matijs commented on .changeset/alle-headings.md
> +---
deze file is niet nodig voor de 1.0.0 publish (er zou meteen een bump naar 2.0.0 voor alle componenten gedaan worden op deze manier)

2024-12-09 23:05 UTC, Robbert approved these changes

2024-12-10 07:10 UTC, hidde commented
thanks Robbert!

2024-12-10 07:29 UTC, Robbert approved these changes

2024-12-10 07:29 UTC, merged